# Site settings
title: WORC
email: youremailaddress@gmail.com
description: Machines should work. Everyone should benefit.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
github_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/will-stedden
twitter_url: https://twitter.com/bonkerfield

# Build settings
markdown: kramdown
